
apiVersion: v1
kind: Service
metadata:
  name: plantsbywebsphere8
  labels:
    app: plantsbywebsphere8
spec:
  ports:
    - port: 9080
  selector:
    app: plantsbywebsphere8
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: plantsbywebsphere8
  name: plantsbywebsphere8
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plantsbywebsphere8
    spec:
      containers:
      - image: mycluster.icp:8500/default/plantsbywebsphere8:latest
        name: plantsbywebsphere8
        ports:
        - containerPort: 9080
          protocol: TCP
